	<style>
		#upper-content-content {
			min-height: 10px;
		}
	</style>
	
	
	<div class="clearfix" style="height: 15px;"></div>
	
	<div id="admin-bar">
		<a href="./admin-view-case-studies.php" >
			<img class="admin-icon" src="./images/menus/menu-case-studies.png" />
		</a>
		<a href="./admin-edit-gallery.php?id=3" >
			<img class="admin-icon" src="./images/menus/menu-gallery-downloads.png" />
		</a>
		<a href="./logout.php" >
			<img class="admin-icon" src="./images/menus/menu-logout.png" style=" float: right;" />
		</a>
		
	</div>
	<div class="clearfix" style="height: 1px;"></div>