
	<div id="admin-bar-gallery">
		<img src="./images/menus/menu-gallery-downloads.png" style="float: left; padding-left: 10px; padding-right: 20px; margin-top: -18px;"/>
		<a href="./admin-edit-gallery.php?id=4" >
			<img class="admin-gallery-icon" src="./images/menus/menu-gallery-assembly.png" />
		</a>
		<a href="./admin-edit-gallery.php?id=5" >
			<img class="admin-gallery-icon" src="./images/menus/menu-gallery-stamping.png" />
		</a>
		<a href="./admin-edit-gallery.php?id=6" >
			<img class="admin-gallery-icon" src="./images/menus/menu-gallery-machining.png" />
		</a>
		<a href="./admin-edit-gallery.php?id=2" >
			<img class="admin-gallery-icon" src="./images/menus/menu-gallery-tooling.png" />
		</a>
		<a href="./admin-edit-gallery.php?id=3" >
			<img class="admin-gallery-icon" src="./images/menus/menu-gallery-prototypes.png" />
		</a>	
	</div>
	<div class="clearfix" style="height: 1px;"></div>