			<!-- start footer.inc -->
			
		</div>
	</div>
	
	<div id="footer-container">
		<div id="footer-content">

	<div class="footer-content">
		<div class="logo-div">
					<img src="images/footer-logo.png" />
				</div>
				<div class="footer-contact-div" style="padding-left:540px;">
					<span class="boldTitle">Mailing Address:</span><br/>
					110 Werlich Drive<br/>
					Cambridge, Ontario<br/>
					Canada, N1T 1N6<br/>
				</div>
				<div class="footer-phone-div">
					<span class="boldTitle">Phone:</span> 519-622-1711<br/>
					<span class="boldTitle">Fax:</span> 519-6221152<br/>
					<span class="boldTitle">Email:</span> <a href="mailto:info@umcmfg.com" style="color:#CCCCCC;font-weight:100;">info@umcmfg.com</a><br/>
				</div>
			</div>
			<div class="clearfix"></div>	
			<div class="line" style="background-image: url('images/hrImg.png');">&nbsp;</div>
			<div class="clearfix"></div>
				<div class="footer-nav">
					<ul>
						<li><a href="">main</a></li>
						<li><a href="">profile</a></li>
						<li><a href="">case studies</a></li>
						<li><a href="">prototypes</a></li>
						<li><a href="">machining</a></li>
						<li><a href="">metal stamping</a></li><br/>
						<li style="margin-left: 150px; float:left"><a href="">Product Assembly</a></li>
						<li><a href="" class="contact" style="margin-top:4px;">Contact</a></li>
					</ul>
				</div>
			<div class="clearfix" style="height: 15px;"></div>
			<div class="ourLink" style="margin-top:-2px;">
				<a href="Http://www.aholattafun.com" target="_blank" style="color:rgb(10,74,226);">
					<span style="color:white; ">
						Website:
					</span> 
					Aholattafun Creative Solutions<br/>
				</a>
			</div>
		</div>
			<div class="clearfix" style="height: 10px;background:"></div>	
	</div>

</body>
</html>